from machine import Pin
from utime import sleep

led1 = Pin(13, Pin.OUT)
led2 = Pin(14, Pin.OUT)
led3 = Pin(15, Pin.OUT)
led4 = Pin(18, Pin.OUT)
led5 = Pin(17, Pin.OUT)
led6 = Pin(16, Pin.OUT)
while True:
    led1.value(1)
    led6.value(1)
    sleep(5)
    led2.value(1)
    led1.value(0)
    sleep(5)
    led3.value(1)
    led4.value(1)
    led6.value(0)
    led2.value(0)
    sleep(5)
    led5.value(1)
    led4.value(0)
    sleep(5)
    led1.value(0)
    led2.value(0)
    led3.value(0)
    led4.value(0)
    led5.value(0)
    led6.value(0)
